### ISSUE TITLE
The last chart will not change with the  slider.

### ISSUE THREAD

**Issue by zhtordinary** [aksnzhy/bitcoin-bubble-index#1]

**Comment by aksnzhy** [comment]
I fixed this issue. Thanks!

**Comment by zhtordinary** [comment]
> I fixed this issue. Thanks!
Your work is really interesting. Thank you for sharing！

**Comment by zhtordinary** [comment]
> I fixed this issue. Thanks!

Your work is really interesting. Thank you for sharing！
